# Generated by Django 4.1.2 on 2022-11-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ndc', models.CharField(choices=[(1, '総記'), (2, '哲学'), (3, '歴史'), (4, '社会科学'), (5, '自然科学'), (6, '技術. 工学'), (7, '産業'), (8, '芸術. 美術'), (9, '言語'), (10, '文学')], max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('point', models.SmallIntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
