# Generated by Django 4.1.2 on 2022-11-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_book_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='point',
            field=models.SmallIntegerField(default=1, max_length=5),
        ),
    ]
