# Generated by Django 4.1.2 on 2022-11-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'BookReview'},
        ),
        migrations.AlterField(
            model_name='book',
            name='point',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
