# Generated by Django 4.1.2 on 2022-11-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ndc',
            field=models.CharField(choices=[(0, '総記'), (1, '哲学'), (2, '歴史'), (3, '社会科学'), (4, '自然科学'), (5, '技術. 工学'), (6, '産業'), (7, '芸術. 美術'), (8, '言語'), (9, '文学')], max_length=255),
        ),
    ]
