# Generated by Django 4.1.2 on 2022-11-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_book_ndc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='point',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=1),
        ),
    ]
