# Generated by Django 4.1.2 on 2022-11-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_book_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='point',
            new_name='rating',
        ),
    ]
