# Generated by Django 4.1.2 on 2022-11-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_book_ndc'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='poster',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
