# Generated by Django 4.1.2 on 2023-02-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_book_poster'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='review_table',
        ),
    ]
